apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello #name for service
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-hello
  ports:
  - port: 3000 #port want to utilize as external port for deployment
    targetPort: 3000
